# Languages, Package Managers

brew "pnpm"

# CLI Tools

brew "colordiff"
brew "gnu-sed"
brew "jq"
brew "mysql"
# https://github.com/ggreer/the_silver_searcher
brew "the_silver_searcher"
# https://tilt.dev/
brew "tilt"
brew "tree"

# Programming

brew "ktlint"
brew "gradle"
