#!/bin/sh

# Homebrew
# https://brew.sh/

if ! has brew
then
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  # Add to $PATH.
  # This command comes from the output of the brew install script.
  echo 'eval "$(/opt/homebrew/bin/brew shellenv)"' >> ~/.zprofile
  # Add to current shell.
  eval "$(/opt/homebrew/bin/brew shellenv)"
fi
