cask_args appdir: "/Applications", require_sha: true

### Browsers ###
cask "google-chrome", args: { require_sha: false }
cask "firefox"

### Messaging & Communications ###
cask "discord"
cask "signal"
cask "slack"
cask "zoom"

### Editors ###
cask "atom"

### Software Engineering ###
cask "jetbrains-toolbox"

### Miscellaneous ###
cask "spotify", args: { require_sha: false }
