#!/bin/sh

# Oh My Zsh
if [ ! -d ~/.oh-my-zsh ]
then
  sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
fi

# Fonts for powerlevel10k.
# https://github.com/romkatv/powerlevel10k#meslo-nerd-font-patched-for-powerlevel10k
# Assume that if one is missing then all are missing.
if [ ! -e "/Library/Fonts/MesloLGS NF Regular.ttf" ]
then
  log "Installing fonts..."
  cd /Library/Fonts
    curl -O "https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS NF Regular.ttf"
    curl -O "https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS NF Bold.ttf"
    curl -O "https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS NF Italic.ttf"
    curl -O "https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS NF Bold Italic.ttf"
  cd -
fi
